### ISSUE TITLE
关于数据

### ISSUE THREAD

**Issue by PushyTao** [ftiasch/ccpc-final-2020#4]
大佬能否提供数据或者是数据的生成方式，orz

**Comment by ftiasch** [comment]
根目录下有 `./doall.sh`，可以生成数据题面

**Comment by PushyTao** [comment]
> 根目录下有 `./doall.sh`，可以生成数据题面

谢谢

**Comment by PushyTao** [comment]
有个问题想请教一下
在根目录下./doall.sh ccpc-final-2020之后，提示：
Please type another input file name
这里的input file name应该是什么东西，需要自己创建还是？
